# Project information
site_name: Docs
site_author: Natron Tech AG
site_description: >-
  Documentation and guides by Natron Tech.

# Repository
repo_url: https://github.com/natrontech/docs
repo_name: natrontech/docs
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2023 Natron Tech AG

# Page tree
nav:
  - Home: index.md
  - Remote Access:
    - Teleport: 
      - access/teleport/index.md
      - Client Installation: access/teleport/client-installation.md
      - Kubernetes Access:
        - Connect Client: access/teleport/k8s-client.md
        - OpenLens: access/teleport/k8s-openlens.md
      - Database Access:
        - pgAdmin: access/teleport/db-pgadmin.md
    - OpenVPN: 
      - access/openvpn/index.md

# Configuration
theme:
  favicon: assets/images/favicon.png
  #logo: assets/images/icon_dark.png
  custom_dir: overrides
  logo_dark_mode: assets/images/icon_white.png
  logo_light_mode: assets/images/icon_dark.png
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - navigation.prune
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Plugins
plugins:
  - search:
      lang: en

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/natrontech
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/natron-tech

# Extra CSS
extra_css:
  - stylesheets/extra.css

# Markdown extensions
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes